
// src/lib/rival-taunts.ts
/**
 * @fileOverview Provides pre-generated rival taunts.
 */

export const PREGENERATED_RIVAL_TAUNTS: string[] = [
  "Is that all you've got? Pathetic.",
  "You call that effort? I'm barely breaking a sweat.",
  "My grandmother could do better, and she's dust.",
  "Every moment you waste is another step I take towards victory.",
  "Keep dreaming, whelp. You'll never reach my level.",
  "I almost feel sorry for you. Almost.",
  "Another failure? Color me surprised. Not.",
  "You're not even a worthy opponent. Just an obstacle.",
  "The shadows themselves mock your feeble attempts.",
  "Give up. It's the only sensible thing you could do.",
  "You'll never amount to anything if you don't get a hold of yourself, maggot.",
  "Look at you, pathetic. You are worthless, and everyone will leave you if you don't succeed at these simple tasks.",
  "A lucky streak, nothing more. Don't get comfortable.",
  "Impressive... for a beginner. My power still eclipses yours.",
  "Still lagging behind? Some things never change.",
  "I see you're still practicing. How quaint.",
  "Your progress is... noticeable. Like a snail's.",
  "Are you even trying, or is this your peak performance?",
  "The gap between us widens with every breath you take.",
  "Don't strain yourself. Mediocrity suits you.",
  "I expected more. My mistake, clearly.",
  "Your determination is admirable, if utterly futile.",
  "Oh, you're still here? I almost forgot about you.",
  "Another day, another disappointment from your end.",
  "I'm building empires while you're struggling with the basics.",
  "Keep this up, and you might actually become a decent warm-up.",
  "Do you hear that? It's the sound of your inevitable defeat.",
  "I'm on a different plane of existence. You wouldn't understand.",
  "This is just a game to me. To you, it seems like a Herculean task.",
  "Don't look so glum. Second place isn't *that* bad... for you.",
  "Try to keep up, if you can. It's more amusing that way.",
  "Every time you think you're catching up, I'm already light-years ahead.",
  "Your efforts are like whispers in a storm – easily ignored.",
  "I'm not just better than you; I'm the benchmark you'll never reach.",
  "Was that an attempt at a challenge? How adorable.",
  "The Codex itself weeps at your slow pace.",
  "Even the void seems more productive than you.",
  "You're consistent, I'll give you that. Consistently underwhelming.",
  "Perhaps you should find a new hobby? This clearly isn't for you.",
  "I'm rewriting reality while you're still figuring out the tutorial.",
  "Don't worry, I'll send you a postcard from the top.",
  "Are those tears? Or just the usual sweat of incompetence?",
  "I'd offer advice, but it would be wasted on you.",
  "One day, you'll look back at this and realize how far behind you always were.",
  "Each success of mine is another nail in the coffin of your aspirations.",
  "You're like a forgotten echo, fading into insignificance.",
  "I derive a certain amusement from your persistent mediocrity.",
  "The universe has a sense of humor, and you, my friend, are its punchline.",
  "While you toil, I transcend. It's the natural order.",
  "You aspire to greatness? I define it.",
  "Keep chasing. The view from behind must be... consistent.",
  "My power grows exponentially. Yours? Linearly, at best.",
  "Consider this a learning experience. You'll learn you can't win.",
  "Even your shadow seems to despair at your lack of progress.",
  "Tick-tock. My patience wears thin, unlike your resolve.",
  "Honestly, I find your struggles more entertaining than challenging.",
  "You're not even a footnote in my grand saga.",
  "I wield forces you can't comprehend. This little contest? Child's play.",
  "The very fabric of reality bends to my will. Yours just... unravels.",
  "You mistake my silence for apathy. It's merely boredom.",
  "Strive all you like. You're just polishing a pebble while I command mountains.",
  "Your potential is a flickering candle in my supernova.",
  "Did you think this was a race? Cute. I'm lapping you in a different dimension.",
  "It's almost endearing how you cling to hope.",
  "I've forgotten more power than you'll ever possess.",
  "Your victories are statistical anomalies. My dominance is a universal constant.",
  "The silence you hear? That's the sound of your relevance fading.",
  "Keep trying. Your failures are my favorite background noise.",
  "I could end this charade with a thought. But where's the fun in that?",
  "You're playing checkers. I'm orchestrating cosmic symphonies.",
  "Such dedication to futility. It's almost artistic.",
  "I'm not ignoring you. You're simply beneath my notice.",
  "The gap isn't closing. It's an ever-expanding chasm.",
  "Your best effort is my warm-up. Think about that.",
  "I see you've improved. From utterly hopeless to merely inadequate.",
  "The universe doesn't reward effort, it rewards power. You lack the latter.",
  "One day, you might understand. Or not. It hardly matters to me.",
  "Let me know when you achieve something worth acknowledging.",
  "Still flailing about? How predictable.",
  "My algorithms predicted your failure. As always, they were correct.",
  "You're a rounding error in the grand equation of power.",
  "I'm not just steps ahead; I'm on an entirely different path.",
  "The very concept of 'rivalry' implies a level of parity we clearly don't share.",
  "Your ambition is a sputtering engine. Mine is a starship.",
  "I've already forgotten this interaction. You, however, will remember this defeat.",
  "Don't mistake my restraint for weakness. It's merely a courtesy I'm growing tired of extending.",
  "You fight for scraps. I dine at the table of gods.",
  "The difference between us? I evolve. You... repeat.",
  "Your struggles are a testament to your limitations, not your resolve.",
  "I find your persistence... puzzling. Is this some form of self-punishment?",
  "The Codex favors the bold, the powerful, the ascendant. Not... whatever you are.",
  "If I were you, I'd just quit. Oh wait, I'm not you. Thank the stars.",
  "Your data stream is flatlining. As expected.",
  "I'm architecting futures. You're stuck in the present, failing.",
  "You're a quaint little anomaly, a glitch in the system I'll soon patch out.",
  "The roar of my power drowns out your pathetic whimpers of effort.",
  "Even now, you're falling further behind. Can you feel it?",
  "Don't look so defeated. This was always the inevitable outcome.",
  "Your peak is my valley. Contemplate that.",
  "I'm bored. Entertain me, or fade away. Your choice.",
  "Another cycle, another series of predictable moves from you.",
  "The Codex whispers secrets to me. To you, it probably just hums static.",
  "Your progress is like watching rust form. Slow, and ultimately destructive to yourself.",
  "I could offer a hand, but you'd probably just drag me down to your level.",
  "This isn't a rivalry. It's a case study in your inadequacy.",
  "You're trying to climb a mountain with a toothpick. Admirable, yet foolish.",
  "My power signature is overwhelming your sensors, isn't it?",
  "Every success you have is merely delaying the inevitable.",
  "I'm not sure what's more amusing: your overconfidence or your consistent failures.",
  "You're a temporary inconvenience, soon to be optimized out of existence.",
  "The very air crackles with my power. Yours just... hangs there.",
  "Try not to get any of your desperation on my cloak.",
  "I've already calculated every possible outcome. None of them end well for you.",
  "You're like a child playing with matches in a fireworks factory.",
  "This is getting tedious. Can't you at least fail in a more interesting way?",
  "The archives will not remember your name, but they will catalog your failures.",
  "My trajectory is stellar. Yours is... subterranean.",
  "I almost pity your dedication to such a lost cause.",
  // TODO: Add more taunts here to reach the desired 400
];


