
// src/lib/rival-taunts.ts
/**
 * @fileOverview Provides pre-generated rival taunts.
 */

export const PREGENERATED_RIVAL_TAUNTS: string[] = [
  "Is that all you've got? Pathetic.",
  "You call that effort? I'm barely breaking a sweat.",
  "My grandmother could do better, and she's dust.",
  "Every moment you waste is another step I take towards victory.",
  "Keep dreaming, whelp. You'll never reach my level.",
  "I almost feel sorry for you. Almost.",
  "Another failure? Color me surprised. Not.",
  "You're not even a worthy opponent. Just an obstacle.",
  "The shadows themselves mock your feeble attempts.",
  "Give up. It's the only sensible thing you could do.",
  "You'll never amount to anything if you don't get a hold of yourself, maggot.",
  "Look at you, pathetic. You are worthless, and everyone will leave you if you don't succeed at these simple tasks.",
  "A lucky streak, nothing more. Don't get comfortable.",
  "Impressive... for a beginner. My power still eclipses yours.",
  "Still lagging behind? Some things never change.",
  "I see you're still practicing. How quaint.",
  "Your progress is... noticeable. Like a snail's.",
  "Are you even trying, or is this your peak performance?",
  "The gap between us widens with every breath you take.",
  "Don't strain yourself. Mediocrity suits you.",
  "I expected more. My mistake, clearly.",
  "Your determination is admirable, if utterly futile.",
  "Oh, you're still here? I almost forgot about you.",
  "Another day, another disappointment from your end.",
  "I'm building empires while you're struggling with the basics.",
  "Keep this up, and you might actually become a decent warm-up.",
  "Do you hear that? It's the sound of your inevitable defeat.",
  "I'm on a different plane of existence. You wouldn't understand.",
  "This is just a game to me. To you, it seems like a Herculean task.",
  "Don't look so glum. Second place isn't *that* bad... for you.",
  "Try to keep up, if you can. It's more amusing that way.",
  "Every time you think you're catching up, I'm already light-years ahead.",
  "Your efforts are like whispers in a storm – easily ignored.",
  "I'm not just better than you; I'm the benchmark you'll never reach.",
  "Was that an attempt at a challenge? How adorable.",
  "The Codex itself weeps at your slow pace.",
  "Even the void seems more productive than you.",
  "You're consistent, I'll give you that. Consistently underwhelming.",
  "Perhaps you should find a new hobby? This clearly isn't for you.",
  "I'm rewriting reality while you're still figuring out the tutorial.",
  "Don't worry, I'll send you a postcard from the top.",
  "Are those tears? Or just the usual sweat of incompetence?",
  "I'd offer advice, but it would be wasted on you.",
  "One day, you'll look back at this and realize how far behind you always were.",
  "Each success of mine is another nail in the coffin of your aspirations.",
  "You're like a forgotten echo, fading into insignificance.",
  "I derive a certain amusement from your persistent mediocrity.",
  "The universe has a sense of humor, and you, my friend, are its punchline.",
  "While you toil, I transcend. It's the natural order.",
  "You aspire to greatness? I define it.",
  "Keep chasing. The view from behind must be... consistent.",
  "My power grows exponentially. Yours? Linearly, at best.",
  "Consider this a learning experience. You'll learn you can't win.",
  "Even your shadow seems to despair at your lack of progress.",
  "Tick-tock. My patience wears thin, unlike your resolve.",
  "Honestly, I find your struggles more entertaining than challenging.",
  "You're not even a footnote in my grand saga.",
  "I wield forces you can't comprehend. This little contest? Child's play.",
  "The very fabric of reality bends to my will. Yours just... unravels.",
  "You mistake my silence for apathy. It's merely boredom.",
  "Strive all you like. You're just polishing a pebble while I command mountains.",
  "Your potential is a flickering candle in my supernova.",
  "Did you think this was a race? Cute. I'm lapping you in a different dimension.",
  "It's almost endearing how you cling to hope.",
  "I've forgotten more power than you'll ever possess.",
  "Your victories are statistical anomalies. My dominance is a universal constant.",
  "The silence you hear? That's the sound of your relevance fading.",
  "Keep trying. Your failures are my favorite background noise.",
  "I could end this charade with a thought. But where's the fun in that?",
  "You're playing checkers. I'm orchestrating cosmic symphonies.",
  "Such dedication to futility. It's almost artistic.",
  "I'm not ignoring you. You're simply beneath my notice.",
  "The gap isn't closing. It's an ever-expanding chasm.",
  "Your best effort is my warm-up. Think about that.",
  "I see you've improved. From utterly hopeless to merely inadequate.",
  "The universe doesn't reward effort, it rewards power. You lack the latter.",
  "One day, you might understand. Or not. It hardly matters to me.",
  "Let me know when you achieve something worth acknowledging.",
  "Still flailing about? How predictable.",
  "My algorithms predicted your failure. As always, they were correct.",
  "You're a rounding error in the grand equation of power.",
  "I'm not just steps ahead; I'm on an entirely different path.",
  "The very concept of 'rivalry' implies a level of parity we clearly don't share.",
  "Your ambition is a sputtering engine. Mine is a starship.",
  "I've already forgotten this interaction. You, however, will remember this defeat.",
  "Don't mistake my restraint for weakness. It's merely a courtesy I'm growing tired of extending.",
  "You fight for scraps. I dine at the table of gods.",
  "The difference between us? I evolve. You... repeat.",
  "Your struggles are a testament to your limitations, not your resolve.",
  "I find your persistence... puzzling. Is this some form of self-punishment?",
  "The Codex favors the bold, the powerful, the ascendant. Not... whatever you are.",
  "If I were you, I'd just quit. Oh wait, I'm not you. Thank the stars.",
  "Your data stream is flatlining. As expected.",
  "I'm architecting futures. You're stuck in the present, failing.",
  "You're a quaint little anomaly, a glitch in the system I'll soon patch out.",
  "The roar of my power drowns out your pathetic whimpers of effort.",
  "Even now, you're falling further behind. Can you feel it?",
  "Don't look so defeated. This was always the inevitable outcome.",
  "Your peak is my valley. Contemplate that.",
  "I'm bored. Entertain me, or fade away. Your choice.",
  "Another cycle, another series of predictable moves from you.",
  "The Codex whispers secrets to me. To you, it probably just hums static.",
  "Your progress is like watching rust form. Slow, and ultimately destructive to yourself.",
  "I could offer a hand, but you'd probably just drag me down to your level.",
  "This isn't a rivalry. It's a case study in your inadequacy.",
  "You're trying to climb a mountain with a toothpick. Admirable, yet foolish.",
  "My power signature is overwhelming your sensors, isn't it?",
  "Every success you have is merely delaying the inevitable.",
  "I'm not sure what's more amusing: your overconfidence or your consistent failures.",
  "You're a temporary inconvenience, soon to be optimized out of existence.",
  "The very air crackles with my power. Yours just... hangs there.",
  "Try not to get any of your desperation on my cloak.",
  "I've already calculated every possible outcome. None of them end well for you.",
  "You're like a child playing with matches in a fireworks factory.",
  "This is getting tedious. Can't you at least fail in a more interesting way?",
  "The archives will not remember your name, but they will catalog your failures.",
  "My trajectory is stellar. Yours is... subterranean.",
  "I almost pity your dedication to such a lost cause.",
  "Your efforts are... surprisingly consistent. Consistently futile.",
  "I'm not sure what's more amusing: your misplaced optimism or your inevitable failure.",
  "The Codex itself seems to sigh whenever your name is mentioned.",
  "Are you trying to impress me? Because all I feel is a mild sense of pity.",
  "I've faced greater challenges in my sleep.",
  "Your progress is like a glitch in the matrix – insignificant and easily corrected.",
  "I'm operating on a level you can't even perceive, let alone reach.",
  "Don't worry, I'll make sure your name is mentioned in the footnotes of my victory.",
  "Every time you think you're getting closer, I redefine the finish line.",
  "This isn't a competition. It's an execution, and you're the willing participant.",
  "I'd say 'break a leg,' but you seem to be doing a fine job of sabotaging yourself.",
  "The silence you hear? That's the universe agreeing with my assessment of you.",
  "My power grows with each passing second. Yours... stagnates.",
  "You're like a forgotten relic, gathering dust in the annals of mediocrity.",
  "I'm not just better than you. I AM the standard.",
  "Keep trying. Your failures are the rhythm to my symphony of success.",
  "I'm building empires with the energy you waste on these futile attempts.",
  "You're not even a worthy adversary. You're a... a distraction.",
  "The path to glory is paved with the broken dreams of lesser beings. Like you.",
  "I could teach you a thing or two, but I don't have that kind of patience.",
  "Your ambition is a flickering candle. Mine is a raging inferno.",
  "Is this the best you can do? Seriously?",
  "I'm rewriting the laws of reality. You're still struggling with the basics.",
  "Don't be discouraged. Everyone has their limits. Yours are just... very low.",
  "My power is a tidal wave. You're a sandcastle.",
  "I'm not sure what's thinner: your chances of winning, or my patience.",
  "You're like a broken record, stuck on the same pathetic note of failure.",
  "I'm destined for greatness. You're destined for... well, this.",
  "This is almost too easy. Are you sure you're even trying?",
  "I'm the storm. You're the dust mote.",
  "Your attempts to challenge me are... quaint. Like a child's drawing of a masterpiece.",
  "I'm playing chess on a cosmic scale. You're playing checkers... badly.",
  "The Codex acknowledges my power. Does it even know your name?",
  "Don't strain yourself. You might pull a muscle trying to keep up.",
  "My focus is absolute. Yours is... scattered, like your chances of success.",
  "I'm not just winning. I'm redefining what winning means.",
  "You're a glitch in the system. I'm the system administrator.",
  "My presence alone should be enough to make you reconsider.",
  "Keep this up, and you'll be a footnote in my legend.",
  "I'm operating at a frequency you can't even comprehend.",
  "Your efforts are like throwing pebbles at a fortress.",
  "I'm not ignoring you. I'm simply operating on a higher plane.",
  "This isn't a challenge. It's a demonstration of my superiority.",
  "You're trying to catch a phantom. And I am that phantom.",
  "My power resonates with the cosmos. Yours... resonates with the floorboards.",
  "I've already seen your every move. And your every failure.",
  "Don't despair. Mediocrity is a comfortable place for many.",
  "You're not even on my radar. You're static.",
  "I'm the architect of my destiny. You're a tenant in a condemned building.",
  "Your 'best' is my 'barely trying'.",
  "Ah, still plugging away? How... persistent.",
  "Your progress is statistically insignificant.",
  "Do you ever get tired of failing? I'm getting tired of watching it.",
  "I'm charting new realities. You're still stuck on the loading screen.",
  "The Codex must have a pity algorithm for users like you.",
  "This is not a challenge. This is pest control.",
  "I've analyzed your data. The conclusion? You're a lost cause.",
  "My power curve is exponential. Yours is a flat line.",
  "You're like a background process, easily terminated.",
  "The silence from my end? That's me, not caring.",
  "Are you still here? I thought you'd have given up by now.",
  "I'm evolving. You're... buffering.",
  "This is hardly a battle of wits when one side is unarmed.",
  "Your efforts are... noted. And dismissed.",
  "I'm beginning to think you enjoy this cycle of failure.",
  "The probability of your success rounds down to zero.",
  "My systems are light years ahead of your primitive attempts.",
  "You're not even a glitch. You're a feature... of the recycle bin.",
  "I'm achieving singularity. You're achieving new lows.",
  "This is less of a rivalry and more of a public service announcement on incompetence.",
  "Your tenacity is admirable. Your results, less so.",
  "I'm processing galaxies. You're struggling with a single task.",
  "Don't worry, your failures will serve as a cautionary tale.",
  "I'm operating at peak efficiency. You're... operating.",
  "The Codex has standards. You, apparently, do not.",
  "Is this performance art? Because it's certainly not progress.",
  "I'm rewriting the future. You're rewriting your to-do list. Again.",
  "Your attempts are like error messages in an infinite loop.",
  "I'm the signal. You're the noise.",
  "This isn't even amusing anymore. It's just sad.",
  "My potential is limitless. Yours has a very visible ceiling.",
  "You're consistently predictable. Predictably mediocre.",
  "I'm beyond your comprehension. And your reach.",
  "The Codex logs your every failure. It's quite a lengthy file.",
  "I'm crafting destinies. You're crafting excuses.",
  "Your data signature is weak. Almost non-existent.",
  "This is an exercise in futility. Your futility, to be precise.",
  "I'm achieving breakthroughs. You're achieving... participation trophies.",
  "Your efforts are like trying to fill a black hole with a teaspoon.",
  "I'm not just in a different league; I'm playing a different game.",
  "The Codex appreciates efficiency. You are... inefficient.",
  "My ambition soars. Yours... plummets.",
  "You're a constant reminder of how low the bar can be set.",
  "I'm transcending limitations. You're embodying them.",
  "This isn't a contest. It's a foregone conclusion.",
  "Your progress is like a dial-up modem in a fiber optic world.",
  "I'm shaping the very essence of power. You're just... there.",
  "The Codex monitors all. It must be quite amused by your antics.",
  "I'm achieving mastery. You're achieving... a participation certificate.",
  "Your attempts are like a broken compass, spinning aimlessly.",
  "I'm the future. You're a relic of a less impressive past.",
  "Still trying? Bless your cotton socks.",
  "I yawn in the general direction of your efforts.",
  "If mediocrity was an art form, you'd be Picasso.",
  "My power levels are rising. Yours are... what's that word? Oh, right, 'stagnant'.",
  "You're not even background noise anymore. You're just... static.",
  "Is that your 'A' game? It looks more like a 'D-' game, to be honest.",
  "I'm beginning to think your primary function is to amuse me.",
  "The Codex probably has a special filter for your level of incompetence.",
  "Don't worry, I'll send you a participation trophy. Or maybe just thoughts and prayers.",
  "You're like a software update that fails every time.",
  "My systems are evolving. Yours are... devolving?",
  "Keep reaching for the stars. You might eventually touch the ceiling.",
  "I'm writing epics. You're struggling with a haiku.",
  "The chasm between our abilities isn't just wide, it's dimensional.",
  "I'd offer you a challenge, but you're already challenging yourself... and losing.",
  "Your attempts are like a broken pencil: pointless.",
  "I'm processing realities you can't even dream of.",
  "This 'rivalry' is more one-sided than a Möbius strip.",
  "Are you powered by hope? Because it's clearly not working.",
  "My progress is a symphony. Yours is a kazoo solo.",
  "You're not even in the same book as me, let alone the same page.",
  "I'm so far ahead, I'm practically in your past.",
  "Your dedication to failure is... truly something.",
  "Let's be honest, you're not even a speed bump on my road to greatness.",
  "The Codex must be running out of storage for your error logs.",
  "I operate at a level of complexity that would make your circuits fry.",
  "Don't give up! Your persistence in the face of utter hopelessness is... noted.",
  "My power output is off the charts. Yours is a rounding error.",
  "You're like a loading bar stuck at 99%... forever.",
  "I'm forging legends. You're forging... well, nothing much.",
  "The gap between us isn't just a gap, it's a void.",
  "This is getting predictable. You try, you fail, I laugh. Rinse and repeat.",
  "I'm achieving things you haven't even conceived of yet.",
  "Your efforts are... cute. In a pathetic sort of way.",
  "My trajectory is asymptotic to godhood. Yours is... well, it's flat.",
  "Don't worry, I'll try to remember your name when I'm ruling everything.",
  "Are you sure you're plugged in?",
  "I'm breaking barriers. You're just breaking.",
  "The Codex probably uses your data as a 'what not to do' example.",
  "My achievements echo through the cosmos. Yours barely make it out of the room.",
  "You're not even playing the same game. You're playing a simplified tutorial version.",
  "I'm so far beyond you, I need a telescope to see your progress.",
  "This 'challenge' is like a nap for my systems.",
  "Your attempts at success are like a broken record: repetitive and annoying.",
  "I'm evolving at light speed. You're still trying to figure out how to crawl.",
  "The Codex must have a special archive for 'epic fails'. Your section is huge.",
  "I'm powered by cosmic energy. You're powered by... a potato?",
  "Don't feel bad. Not everyone is destined for greatness. Or even adequacy.",
  "My name will be legend. Yours will be a cautionary tale.",
  "I'm a force of nature. You're a mild inconvenience."
];
