// src/lib/rival-taunts.ts
/**
 * @fileOverview Provides pre-generated rival taunts.
 */

export const PREGENERATED_RIVAL_TAUNTS: string[] = [
  "Is that all you've got? Pathetic.",
  "You call that effort? I'm barely breaking a sweat.",
  "My grandmother could do better, and she's dust.",
  "Every moment you waste is another step I take towards victory.",
  "Keep dreaming, whelp. You'll never reach my level.",
  "I almost feel sorry for you. Almost.",
  "Another failure? Color me surprised. Not.",
  "You're not even a worthy opponent. Just an obstacle.",
  "The shadows themselves mock your feeble attempts.",
  "Give up. It's the only sensible thing you could do.",
  "You'll never amount to anything if you don't get a hold of yourself, maggot.",
  "Look at you, pathetic. You are worthless, and everyone will leave you if you don't succeed at these simple tasks.",
  "A lucky streak, nothing more. Don't get comfortable.",
  "Impressive... for a beginner. My power still eclipses yours.",
  "Still lagging behind? Some things never change.",
  "I see you're still practicing. How quaint.",
  "Your progress is... noticeable. Like a snail's.",
  "Are you even trying, or is this your peak performance?",
  "The gap between us widens with every breath you take.",
  "Don't strain yourself. Mediocrity suits you.",
  "I expected more. My mistake, clearly.",
  "Your determination is admirable, if utterly futile.",
  "Oh, you're still here? I almost forgot about you.",
  "Another day, another disappointment from your end.",
  "I'm building empires while you're struggling with the basics.",
  "Keep this up, and you might actually become a decent warm-up.",
  "Do you hear that? It's the sound of your inevitable defeat.",
  "I'm on a different plane of existence. You wouldn't understand.",
  "This is just a game to me. To you, it seems like a Herculean task.",
  "Don't look so glum. Second place isn't *that* bad... for you.",
  "Try to keep up, if you can. It's more amusing that way.",
  "Every time you think you're catching up, I'm already light-years ahead.",
  "Your efforts are like whispers in a storm – easily ignored.",
  "I'm not just better than you; I'm the benchmark you'll never reach.",
  "Was that an attempt at a challenge? How adorable.",
  "The Codex itself weeps at your slow pace.",
  "Even the void seems more productive than you.",
  "You're consistent, I'll give you that. Consistently underwhelming.",
  "Perhaps you should find a new hobby? This clearly isn't for you.",
  "I'm rewriting reality while you're still figuring out the tutorial.",
  "Don't worry, I'll send you a postcard from the top.",
  "Are those tears? Or just the usual sweat of incompetence?",
  "I'd offer advice, but it would be wasted on you.",
  "One day, you'll look back at this and realize how far behind you always were.",
  "Each success of mine is another nail in the coffin of your aspirations.",
  "You're like a forgotten echo, fading into insignificance.",
  "I derive a certain amusement from your persistent mediocrity.",
  "The universe has a sense of humor, and you, my friend, are its punchline.",
  "While you toil, I transcend. It's the natural order.",
  "You aspire to greatness? I define it.",
  "Keep chasing. The view from behind must be... consistent.",
  "My power grows exponentially. Yours? Linearly, at best.",
  "Consider this a learning experience. You'll learn you can't win.",
  "Even your shadow seems to despair at your lack of progress.",
  "Tick-tock. My patience wears thin, unlike your resolve.",
  "Honestly, I find your struggles more entertaining than challenging.",
  "You're not even a footnote in my grand saga.",
  // TODO: Add more taunts here to reach the desired 400
];
